---
title: "Review of Water Thresholds - Gnangara"
author: "Christopher Kavazos, Grant Buller, Pierre Horwitz, Ray Froend"
date: "16/09/2019"
output:
  word_document: default
  pdf_document: default
fig_caption: yes
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
library(flextable)
library(ggplot2)
library(ggpubr)
source("functions.R")
knitr::opts_chunk$set(fig.width=6, fig.height=7, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```

# Introduction

This report details an analysis that reviews the ecological impacts of revised proposed water level thresholds for wetlands in the Gnangara mound.

Full analysis can be found [here] (https://github.com/ChrisKav/DWER-Thresholds-2019)

```{r, echo=FALSE}
load("Refined_data.RData")
```

# EMP 173

```{r EMP173_water, echo = FALSE, results = 'asis'}
load("EMP_173/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at EMP 173")
```

```{r EMP173_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of EMP 173", results = 'asis'}
Site.GW.plots$emp173.p
```

```{r EMP173_strat, fig.cap="\\label{fig:II} ", results = 'asis'}
load("EMP_173/boral_models.RData")
strat.plots <- stratiplotter(vegfit.mod3)
```

```{r EMP173_ord, fig.cap="\\label{fig:II} Ordination plot with full residual model on the left and a model on the right showing residual variation after the effect of groundwater levels were accounted for", results = 'asis'}
load("EMP_173/boral_models.RData")
ggarrange(veg.ord1, veg.ord2, ncol=2)
```

```{r EMP173_post, fig.cap="\\label{fig:III} Mean regression coefficients (dots) and 95% credible intervals (bars) for effect of groundwater level on vegetation species cover abundances. Only those species with coefficients significanlty different to zero are shown", results = 'asis'}
load("EMP_173/Vegetation/beta_plot.RData")
beta.plot
```

# EMP 78

```{r EMP78_water, echo = FALSE, results = 'asis'}
load("EMP_78/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at EMP 78")
```

```{r EMP78_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of EMP 78", results = 'asis'}
Site.GW.plots$emp78.p
```

```{r EMP78_strat, fig.cap="\\label{fig:II} ", results = 'asis'}
load("EMP_78/boral_models.RData")
strat.plots <- stratiplotter(vegfit.mod3)
```

```{r EMP78_ord, fig.cap="\\label{fig:I} Ordination plot with full residual model on the left and a model on the right showing residual variation after the effect of groundwater levels were accounted for", results = 'asis'}
load("EMP_78/boral_models.RData")
ggarrange(veg.ord1, veg.ord2, ncol=2)
```

```{r EMP78_post, fig.cap="\\label{fig:III} Mean regression coefficients (dots) and 95% credible intervals (bars) for effect of groundwater level on vegetation species cover abundances. Only those species with coefficients significanlty different to zero are shown", results = 'asis'}
load("EMP_78/Vegetation/beta_plot.RData")
beta.plot
```

# Gingin

```{r Gingin_water, echo = FALSE, results = 'asis'}
load("Gingin/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at Gingin")
```

```{r Gingin_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of Gingin", results = 'asis'}
Site.GW.plots$gin.p
```

# Goollelal

```{r Goollelal_water, echo = FALSE, results = 'asis'}
  load("Goollelal/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at Goollelal")
```

```{r Goollelal_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of Goollelal", results = 'asis'}
Site.GW.plots$gool.p
```

```{r Goollelal_strat, fig.cap="\\label{fig:II} ", results = 'asis'}
load("Goollelal/boral_models.RData")
strat.plots <- stratiplotter(vegfit.mod3)
```

```{r Goollelal_ord, fig.cap="\\label{fig:I} Ordination plot with full residual model on the left and a model on the right showing residual variation after the effect of groundwater levels were accounted for", results = 'asis'}
load("Goollelal/boral_models.RData")
ggarrange(veg.ord1, veg.ord2, ncol=2)
```

```{r Goollelal_post, fig.cap="\\label{fig:III} Mean regression coefficients (dots) and 95% credible intervals (bars) for effect of groundwater level on vegetation species cover abundances. Only those species with coefficients significanlty different to zero are shown", results = 'asis'}
load("Goollelal/Vegetation/beta_plot.RData")
beta.plot
```

# Gwelup

```{r Gwelup_water, echo = FALSE, results = 'asis'}
load("Gwelup/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at Gwelup")
```

```{r Gwelup_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of Gwelup", results = 'asis'}
Site.GW.plots$gwel.p
```

```{r Gwelup_strat, fig.cap="\\label{fig:II} ", results = 'asis'}
load("Gwelup/boral_models.RData")
strat.plots <- stratiplotter(vegfit.mod3)
```

```{r Gwelup_ord, fig.cap="\\label{fig:I} Ordination plot with full residual model on the left and a model on the right showing residual variation after the effect of groundwater levels were accounted for", results = 'asis'}
load("Gwelup/boral_models.RData")
ggarrange(veg.ord1, veg.ord2, ncol=2)
```

```{r Gwelup_post, fig.cap="\\label{fig:III} Mean regression coefficients (dots) and 95% credible intervals (bars) for effect of groundwater level on vegetation species cover abundances. Only those species with coefficients significanlty different to zero are shown", results = 'asis'}
load("Gwelup/Vegetation/beta_plot.RData")
beta.plot
```

# Jandabup

```{r Jandabup_water, echo = FALSE, results = 'asis'}
load("Jandabup/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at Jandabup")
```

```{r Jandabup_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of Jandabup", results = 'asis'}
Site.GW.plots$jand.p
```

```{r Jandabup_strat, fig.cap="\\label{fig:II} ", results = 'asis'}
load("Jandabup/boral_models.RData")
strat.plots <- stratiplotter(vegfit.mod3)
```

```{r Jandabup_ord, fig.cap="\\label{fig:I} Ordination plot with full residual model on the left and a model on the right showing residual variation after the effect of groundwater levels were accounted for", results = 'asis'}
load("Jandabup/boral_models.RData")
ggarrange(veg.ord1, veg.ord2, ncol=2)
```

```{r Jandabup_post, fig.cap="\\label{fig:III} Mean regression coefficients (dots) and 95% credible intervals (bars) for effect of groundwater level on vegetation species cover abundances. Only those species with coefficients significanlty different to zero are shown", results = 'asis'}
load("Jandabup/Vegetation/beta_plot.RData")
beta.plot
```

# Joondalup

```{r Joondalup_Nth_water, echo = FALSE, results = 'asis'}
load("Joondalup_Nth/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at Lake Joondalup")
```

```{r Joondalup_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of Joondalup", results = 'asis'}
Site.GW.plots$joon.p
```

```{r Joondalup_Nth, fig.cap="\\label{fig:II} ", results = 'asis'}
load("Joondalup_Nth/boral_models.RData")
strat.plots <- stratiplotter(vegfit.mod3)
```


```{r Joondalup_Sth_strat, fig.cap="\\label{fig:II} ", results = 'asis'}
load("Joondalup_Sth/boral_models.RData")
strat.plots <- stratiplotter(vegfit.mod3)
```

```{r Joondalup_Nth_ord, fig.cap="\\label{fig:I} Ordination plot with full residual model on the left and a model on the right showing residual variation after the effect of groundwater levels were accounted for", results = 'asis'}
load("Joondalup_Nth/boral_models.RData")
ggarrange(veg.ord1, veg.ord2, ncol=2)
```

```{r Joondalup_Sth_ord, fig.cap="\\label{fig:I} Ordination plot with full residual model on the left and a model on the right showing residual variation after the effect of groundwater levels were accounted for", results = 'asis'}
load("Joondalup_Sth/boral_models.RData")
ggarrange(veg.ord1, veg.ord2, ncol=2)
```

```{r Joondalup_Nth_post, fig.cap="\\label{fig:III} Mean regression coefficients (dots) and 95% credible intervals (bars) for effect of groundwater level on vegetation species cover abundances. Only those species with coefficients significanlty different to zero are shown", results = 'asis'}
load("Joondalup_Nth/Vegetation/beta_plot.RData")
beta.plot
```

```{r Joondalup_Sth_post, fig.cap="\\label{fig:III} Mean regression coefficients (dots) and 95% credible intervals (bars) for effect of groundwater level on vegetation species cover abundances. Only those species with coefficients significanlty different to zero are shown", results = 'asis'}
load("Joondalup_Sth/Vegetation/beta_plot.RData")
beta.plot
```

# Lexia 186

```{r Lexia186_water, echo = FALSE, results = 'asis'}
load("Lexia_186/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at Lexia 186")
```

```{r Lexia186_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of Lexia 186", results = 'asis'}
Site.GW.plots$lex186.p
```

```{r Lexia186_strat, fig.cap="\\label{fig:II} ", results = 'asis'}
load("Lexia_186/boral_models.RData")
strat.plots <- stratiplotter(vegfit.mod3)
```

```{r Lexia186_ord, fig.cap="\\label{fig:I} Ordination plot with full residual model on the left and a model on the right showing residual variation after the effect of groundwater levels were accounted for", results = 'asis'}
load("Lexia_186/boral_models.RData")
ggarrange(veg.ord1, veg.ord2, ncol=2)
```

```{r Lexia186_post, fig.cap="\\label{fig:III} Mean regression coefficients (dots) and 95% credible intervals (bars) for effect of groundwater level on vegetation species cover abundances. Only those species with coefficients significanlty different to zero are shown", results = 'asis'}
load("Lexia_186/Vegetation/beta_plot.RData")
beta.plot
```

# Loch McNess

```{r Loch_McNess_water, echo = FALSE, results = 'asis'}
load("Loch_McNess/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at Loch McNess")
```

```{r Loch_McNess_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of Loch McNess", results = 'asis'}
Site.GW.plots$mcness.p
```

```{r Loch_McNess_strat, fig.cap="\\label{fig:II} ", results = 'asis'}
load("Loch_McNess/boral_models.RData")
strat.plots <- stratiplotter(vegfit.mod3)
```

```{r Loch_McNess_ord, fig.cap="\\label{fig:I} Ordination plot with full residual model on the left and a model on the right showing residual variation after the effect of groundwater levels were accounted for", results = 'asis'}
load("Loch_McNess/boral_models.RData")
ggarrange(veg.ord1, veg.ord2, ncol=2)
```

```{r Loch_McNess_post, fig.cap="\\label{fig:III} Mean regression coefficients (dots) and 95% credible intervals (bars) for effect of groundwater level on vegetation species cover abundances. Only those species with coefficients significanlty different to zero are shown", results = 'asis'}
load("Loch_McNess/Vegetation/beta_plot.RData")
beta.plot
```

# Mariginiup

```{r Mariginiup_water, echo = FALSE, results = 'asis'}
load("Mariginiup/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at Mariginiup")
```

```{r Mariginiup_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of Mariginiup", results = 'asis'}
Site.GW.plots$marig.p
```

```{r Mariginiup_strat, fig.cap="\\label{fig:II} ", results = 'asis'}
load("Mariginiup/boral_models.RData")
strat.plots <- stratiplotter(vegfit.mod3)
```

```{r Mariginiup_ord, fig.cap="\\label{fig:I} Ordination plot with full residual model on the left and a model on the right showing residual variation after the effect of groundwater levels were accounted for", results = 'asis'}
load("Mariginiup/boral_models.RData")
ggarrange(veg.ord1, veg.ord2, ncol=2)
```

```{r Mariginiup_post, fig.cap="\\label{fig:III} Mean regression coefficients (dots) and 95% credible intervals (bars) for effect of groundwater level on vegetation species cover abundances. Only those species with coefficients significanlty different to zero are shown", results = 'asis'}
load("Mariginiup/Vegetation/beta_plot.RData")
beta.plot
```

# MM59B

```{r MM59B_water, echo = FALSE, results = 'asis'}
load("MM59B/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at MM59B")
```

```{r MM59B_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of MM59B", results = 'asis'}
Site.GW.plots$MM59B.p
```

# Nowergup

```{r Nowergup_water, echo = FALSE, results = 'asis'}
load("Nowergup_Nth/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at Nowergup")
```

```{r Nowergup_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of Nowergup", results = 'asis'}
Site.GW.plots$nower.p
```

```{r Nowergup_Nth_strat, fig.cap="\\label{fig:II} ", results = 'asis'}
load("Nowergup_Nth/boral_models.RData")
strat.plots <- stratiplotter(vegfit.mod3)
```

```{r Nowergup_Sth_strat, fig.cap="\\label{fig:II} ", results = 'asis'}
load("Nowergup_Sth/boral_models.RData")
strat.plots <- stratiplotter(vegfit.mod3)
```

```{r Nowergup_Nth_ord, fig.cap="\\label{fig:I} Ordination plot with full residual model on the left and a model on the right showing residual variation after the effect of groundwater levels were accounted for", results = 'asis'}
load("Nowergup_Nth/boral_models.RData")
ggarrange(veg.ord1, veg.ord2, ncol=2)
```

```{r Nowergup_Sth_ord, fig.cap="\\label{fig:I} Ordination plot with full residual model on the left and a model on the right showing residual variation after the effect of groundwater levels were accounted for", results = 'asis'}
load("Nowergup_Sth/boral_models.RData")
ggarrange(veg.ord1, veg.ord2, ncol=2)
```

```{r Nowergup_Nth_post, fig.cap="\\label{fig:III} Mean regression coefficients (dots) and 95% credible intervals (bars) for effect of groundwater level on vegetation species cover abundances. Only those species with coefficients significanlty different to zero are shown", results = 'asis'}
load("Nowergup_Nth/Vegetation/beta_plot.RData")
beta.plot
```

```{r Nowergup_Sth_post, fig.cap="\\label{fig:III} Mean regression coefficients (dots) and 95% credible intervals (bars) for effect of groundwater level on vegetation species cover abundances. Only those species with coefficients significanlty different to zero are shown", results = 'asis'}
load("Nowergup_Sth/Vegetation/beta_plot.RData")
beta.plot
```

# Pipidinny

```{r Pipidinny_water, echo = FALSE, results = 'asis'}
load("Pipidinny/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at Pipidinny")
```

```{r Pipidinny_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of Pipidinny", results = 'asis'}
Site.GW.plots$pipi.p
```

# PM9

```{r PM9_water, echo = FALSE, results = 'asis'}
load("PM9/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at PM9")
```

```{r PM9_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of PM9", results = 'asis'}
Site.GW.plots$PM9.p
```

# Quin Brook

```{r Quin_Brook_water, echo = FALSE, results = 'asis'}
load("Quin_Brook/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at Quin Brook")
```

```{r Quin_Brook_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of Quin Brook", results = 'asis'}
Site.GW.plots$quin.p
```

# Wilgarup

```{r Wilgarup_water, echo = FALSE, results = 'asis'}
load("Wilgarup/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at Wilgarup")
```

```{r Wilgarup_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of Wilgarup", results = 'asis'}
Site.GW.plots$wilg.p
```

```{r Wilgarup_strat, fig.cap="\\label{fig:II} ", results = 'asis'}
load("Wilgarup/boral_models.RData")
strat.plots <- stratiplotter(vegfit.mod3)
```

```{r Wilgarup_ord, fig.cap="\\label{fig:I} Ordination plot with full residual model on the left and a model on the right showing residual variation after the effect of groundwater levels were accounted for", results = 'asis'}
load("Wilgarup/boral_models.RData")
ggarrange(veg.ord1, veg.ord2, ncol=2)
```

```{r Wilgarup_post, fig.cap="\\label{fig:III} Mean regression coefficients (dots) and 95% credible intervals (bars) for effect of groundwater level on vegetation species cover abundances. Only those species with coefficients significanlty different to zero are shown", results = 'asis'}
load("Wilgarup/Vegetation/beta_plot.RData")
beta.plot
```

# WM1

```{r WM1_water, echo = FALSE, results = 'asis'}
load("EMP_173/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at EMP 173")
```

```{r WM1_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of WM1", results = 'asis'}
Site.GW.plots$WM1.p
```

# WM2

```{r WM2_water, echo = FALSE, results = 'asis'}
load("EMP_173/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at WM2")
```

```{r WM2_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of WM2", results = 'asis'}
Site.GW.plots$WM2.p
```

# WM8

```{r WM8_water, echo = FALSE, results = 'asis'}
load("WM8/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at WM8")
```

```{r WM8_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of WM8", results = 'asis'}
Site.GW.plots$WM8.p
```

# Yonderup

```{r Yonderup_water, echo = FALSE, results = 'asis'}
load("Yonderup/water_level.RData")

set_caption(flextable(sw.sum), "Five year summaries of surface water level data at Yonderup")
```

```{r Yoderup_water_plot, fig.cap="\\label{fig:I} Ground and surface water levels recorded at bores and staff gauges in the vicinity of Yonderup", results = 'asis'}
Site.GW.plots$yond.p
```

```{r Yonderup_strat, fig.cap="\\label{fig:II} ", results = 'asis'}
load("Yonderup/boral_models.RData")
strat.plots <- stratiplotter(vegfit.mod3)
```

```{r Yonderup_ord, fig.cap="\\label{fig:I} Ordination plot with full residual model on the left and a model on the right showing residual variation after the effect of groundwater levels were accounted for", results = 'asis'}
load("Yonderup/boral_models.RData")
ggarrange(veg.ord1, veg.ord2, ncol=2)
```

```{r Yonderup_post, fig.cap="\\label{fig:III} Mean regression coefficients (dots) and 95% credible intervals (bars) for effect of groundwater level on vegetation species cover abundances. Only those species with coefficients significanlty different to zero are shown", results = 'asis'}
load("Yonderup/Vegetation/beta_plot.RData")
beta.plot
```
